name: teDOT
on: 
  workflow_dispatch:
    inputs: 
      teToken: 
        required: false
        type: string
        description: "ThousandEyes Oauth Token"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install requests
    - name: Run the Code and add Tests to ThousandEyes
      run: python3 teDOTbyLabel.py ${{ inputs.teToken }}