name: teDOT
on: 
  workflow_dispatch:
    inputs: 
      teToken: 
        required: false
        type: string
        description: "ThousandEyes Oauth Token"

jobs:
  Test_Diagrams:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Dependencies
      run: pip install requests

    - name: Create Mermaid Code
      run: python3 teDOTbyLabels.py ${{ inputs.teToken }}

    - name: Go to Mermaid, Excalidraw or Draw.io
      run: echo "https://mermaid.live/" && echo "https://excalidraw.com/" && echo "https://app.diagrams.net/"

#    - name: Upload Executable as Artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: mermaid_diagram
#        path: mermaid_diagram.md


  Alert_Diagrams:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Dependencies
      run: pip install requests

    - name: Create Mermaid Code
      run: python3 teDOTbyAlerts.py ${{ inputs.teToken }}